---

- name: Install PHP and associated packages
  apt: name=php5 state=latest

- name: Install PHP GD library
  apt: name=php5-gd state=latest
  notify:
   - restart apache2

- name: Install other php packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php5-curl
    - php5-mcrypt
