---

- hosts: drupal_hosts

  sudo: yes

  vars:
    - db_name: drupal
    - db_user: drupal_user
    - db_password: 58145Abc!
    - db_host: localhost
    - http_port: 80
    - domain: comodoycerca.com

  roles:
   - inline
