---

- name: Install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: Enable mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: Apache2 listen on port {{ http_port }}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port  }}" state=present
  notify:
    - restart apache2

- name: Apache2 virtualhost on port {{ http_port  }}
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port  }}>"
  notify:
    - restart apache2

- name: Create virtual host file
  template: src=../templates/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify:
    - restart apache2
